apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hack-video-worker
  namespace: hack-video-worker
  labels:
    app: hack-video-worker
    tier: autoscaler
  annotations:
    maintainer: "SOAT - Grupo 75"
    description: "HPA para autoescalonamento do backend com base na utilização de CPU"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hack-video-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
