apiVersion: v1
kind: Secret
metadata:
  name: hack-video-worker-secret
  namespace: hack-video-worker
  labels:
    app: hack-video-worker
    tier: backend
  annotations:
    maintainer: "SOAT - Grupo 75"
    description: "Segredos para acesso ao banco de dados PostgreSQL via aplicação"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
